jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: create bottom-stl
        uses: pkoehlers/openscad-build-action@v1
        with:
          input-file: "ABC WLED Controller Board V43 enclosure bottom.scad"
          output-file: "ABC WLED Controller Board V43 enclosure bottom.stl"

      - name: create top-stl
        uses: pkoehlers/openscad-build-action@v1
        with:
          input-file: "ABC WLED Controller Board V43 enclosure top.scad"
          output-file: "ABC WLED Controller Board V43 enclosure top.stl"

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      # use release body in the same job
      - name: Upload the release files
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: "*.stl"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          body: ${{ steps.git-cliff.outputs.content }}
